name: "deploy"
description: "voicevox_coreをデプロイする"
inputs:
  artifact_name:
    description: "デプロイするartifact名"
    required: true
  target_os:
    description: "ターゲットのOS"
    required: true
  repo_token:
    description: repositoryのトークン
    required: true
  version:
    description: "version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set ASSET_NAME env var
      shell: bash
      run: echo "ASSET_NAME=voicevox_core-${{ inputs.artifact_name }}-${{ inputs.version }}" >> $GITHUB_ENV
    - name: Organize artifact
      shell: bash
      run: |
        mkdir -p "artifact/${{ env.ASSET_NAME }}"
        cp -v target/core.h "artifact/${{ env.ASSET_NAME }}"
        cp -v target/release/*.{dll,so,dylib} "artifact/${{ env.ASSET_NAME }}"
        echo "${{ env.VERSION }}" > "artifact/${{ env.ASSET_NAME }}/VERSION"
        cp -v README.md "artifact/${{ env.ASSET_NAME }}/README.txt"
    - name: Archive artifact
      shell: bash
      run: |
        cd artifact
        zip -r "${{ env.ASSET_NAME }}.zip" "artifact/${{ env.ASSET_NAME }}"
    - name: Upload to Release
      if: env.VERSION != 'DEBUG' && env.SKIP_UPLOADING_RELEASE_ASSET == '0'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ inputs.repo_token }}
        prerelease: true
        tag: ${{ env.VERSION }}
        file: ${{ env.ASSET_NAME }}.zip
